# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted VS2017
  demands:
    - DotNetFramework
    - msbuild
    - visualstudio
    - vstest

steps:
- task: VSBuild@1
  displayName: "Build solution source\\InPlaceFuzzing.sln"
  inputs:
    solution: "SampleFuzzingJobs\\InPlaceFuzzing\\inplacefuzzing\\inplacefuzzing.sln"
    vsVersion: "15.0"
    msbuildArgs: /p:RestorePackages=false" /m:4
    platform: "$(BuildPlatform)"
    configuration: "$(BuildConfiguration)"
    clean: false
    createLogFile: true
    maximumCpuCount: false
    restoreNugetPackages: false
    msbuildArchitecture: x86


- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'SampleFuzzingJobs\InPlaceFuzzing\inplacefuzzingSample.nuspec'
    versioningScheme: 'byPrereleaseNumber'
    msbuildArchitecture: x86


- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/6b4e3a7d-b009-4842-b76e-fb9a587cdc50'